const sb=window.tidefallSupabase;
const $=id=>document.getElementById(id);
const loginForm=$('loginForm'), signupForm=$('signupForm'), authPanel=$('authPanel'), profilePanel=$('profilePanel');
function mode(which){loginForm.classList.toggle('hidden',which!=='login');signupForm.classList.toggle('hidden',which!=='signup');$('authStatus').textContent='';}
function prettyAuthError(error){if(!error)return'';return String(error.message||error);}
$('showLogin').onclick=()=>mode('login'); $('showSignup').onclick=()=>mode('signup');
loginForm.onsubmit=async e=>{e.preventDefault();$('authStatus').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});$('authStatus').textContent=error?prettyAuthError(error):'Welcome back.';if(!error) render();};
signupForm.onsubmit=async e=>{e.preventDefault();$('authStatus').textContent='Creating account…';const username=$('signupUsername').value.trim();const display_name=$('signupDisplay').value.trim();const email=$('signupEmail').value.trim();const {data,error}=await sb.auth.signUp({email,password:$('signupPassword').value,options:{data:{username,display_name}}});if(error){$('authStatus').textContent=prettyAuthError(error);return;}$('authStatus').textContent=data.session?'Account created. You are signed in.':'Account created.';if(data.session) render();};
$('forgotPassword').onclick=async()=>{const email=$('loginEmail').value.trim();if(!email){$('authStatus').textContent='Enter your email first.';return;}const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:'https://tidefall.com.au/account.html'});$('authStatus').textContent=error?prettyAuthError(error):'Password reset email sent.';};
$('logoutButton').onclick=async()=>{await sb.auth.signOut();render();};
$('saveProfile').onclick=async()=>{const {data:{user}}=await sb.auth.getUser();if(!user)return;const {error}=await sb.from('profiles').update({display_name:$('editDisplay').value.trim(),username:$('editUsername').value.trim().toLowerCase()}).eq('id',user.id);$('profileStatus').textContent=error?error.message:'Saved.';if(!error) render();};
async function render(){const {data:{user}}=await sb.auth.getUser();authPanel.classList.toggle('hidden',!!user);profilePanel.classList.toggle('hidden',!user);if(!user)return;const {data,error}=await sb.from('profiles').select('username,display_name').eq('id',user.id).single();if(error){$('profileStatus').textContent=error.message;return;}$('profileName').textContent=data.display_name||data.username||'Tidefall user';$('profileEmail').textContent=user.email||'';$('editDisplay').value=data.display_name||'';$('editUsername').value=data.username||'';}
sb.auth.onAuthStateChange(()=>render());render();