const MODERATION_DAYS=30,RECENTLY_DELETED_DAYS=30,BUCKET='wardrobe-private',sb=window.tidefallSupabase;
const camera=document.getElementById('camera'),startCameraBtn=document.getElementById('startCamera'),captureBtn=document.getElementById('capturePhoto'),cameraStatus=document.getElementById('cameraStatus'),cameraPlaceholder=document.getElementById('cameraPlaceholder'),captureCanvas=document.getElementById('captureCanvas'),gallery=document.getElementById('gallery'),emptyGallery=document.getElementById('emptyGallery'),toast=document.getElementById('wardrobeToast'),outfitOverlay=document.getElementById('outfitOverlay'),outfitLabel=document.getElementById('outfitLabel'),authGateTitle=document.getElementById('authGateTitle'),authGateText=document.getElementById('authGateText'),accountLink=document.getElementById('accountLink');
let stream=null,currentGallery='active',currentOutfit='brannor',currentUser=null;
const addDays=(d,n)=>new Date(d).getTime()+n*86400000;
function showToast(m){if(!toast)return;toast.textContent=m;toast.classList.add('show');clearTimeout(window.__wardrobeToast);window.__wardrobeToast=setTimeout(()=>toast.classList.remove('show'),2800)}
function formatDate(v){return new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))}
function daysRemaining(v){return Math.max(0,Math.ceil((new Date(v).getTime()-Date.now())/86400000))}
function syncTabs(){document.querySelectorAll('.gallery-tab').forEach(t=>t.classList.toggle('active',t.dataset.gallery===currentGallery))}
async function refreshAuth(){const{data:{user}}=await sb.auth.getUser();currentUser=user||null;startCameraBtn.disabled=false;if(stream)captureBtn.disabled=false;if(currentUser){authGateTitle.textContent='Signed in';authGateText.textContent=currentUser.email?`Photos will save to ${currentUser.email}`:'Photos will save to your Tidefall account.';accountLink.textContent='My Account';emptyGallery.textContent='No photos here yet.'}else{authGateTitle.textContent='Camera ready';authGateText.innerHTML='You can try the Wardrobe without an account. <a href="account.html" style="color:#fff;text-decoration:underline">Sign in or create an account</a> to save photos to your Camera Roll.';accountLink.textContent='Sign In';emptyGallery.textContent='Sign in to load your Camera Roll.'}await renderGallery()}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;camera.srcObject=null;cameraPlaceholder.classList.remove('hidden');captureBtn.disabled=true;startCameraBtn.textContent='Start Camera'}
async function startCamera(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera is not supported in this browser.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:1600}},audio:false});camera.srcObject=stream;await camera.play().catch(()=>{});cameraPlaceholder.classList.add('hidden');captureBtn.disabled=false;startCameraBtn.textContent='Camera On';cameraStatus.textContent=currentUser?'Camera ready. Photos you take save privately to your Tidefall Camera Roll.':'Camera ready. You can try outfits now; sign in when you take a photo so it can be saved.'}catch(e){console.error(e);cameraStatus.textContent='Camera access was blocked or unavailable. Check the camera permission beside the address bar and try again.';showToast('Camera could not start.')}}
function drawOutfit(ctx,w,h){const cx=w/2,top=h*.49,bw=w*.39,bh=h*.39,p={brannor:['#173b52','#081923'],riptide:['#167d98','#052c3b'],proving:['#474e60','#151922']},[a,b]=p[currentOutfit]||p.brannor,g=ctx.createLinearGradient(cx,top,cx,top+bh);g.addColorStop(0,a);g.addColorStop(1,b);ctx.save();ctx.globalAlpha=.78;ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(cx-bw*.68,top,bw*1.36,bh*.25,40);ctx.fill();ctx.beginPath();ctx.roundRect(cx-bw/2,top+bh*.08,bw,bh,42);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=Math.max(2,w*.003);ctx.stroke();ctx.fillStyle='rgba(255,255,255,.9)';ctx.font=`700 ${Math.max(18,w*.025)}px Georgia`;ctx.textAlign='center';ctx.fillText(outfitLabel.textContent,cx,top+bh*.58);ctx.restore()}
async function uploadPhotoBlob(blob){const id=crypto.randomUUID(),path=`${currentUser.id}/${id}.jpg`;const{error:u}=await sb.storage.from(BUCKET).upload(path,blob,{contentType:'image/jpeg',upsert:false,cacheControl:'3600'});if(u)throw u;const{error:r}=await sb.from('wardrobe_photos').insert({id,user_id:currentUser.id,storage_path:path,outfit:currentOutfit,state:'active',posted:false});if(r){await sb.storage.from(BUCKET).remove([path]);throw r}return id}
async function capturePhoto(){if(!stream||!camera.videoWidth)return;if(!currentUser){showToast('Sign in to save this photo to your Camera Roll.');location.href='account.html?return=wardrobe.html';return}captureBtn.disabled=true;cameraStatus.textContent='Saving securely…';try{const w=camera.videoWidth,h=camera.videoHeight;captureCanvas.width=w;captureCanvas.height=h;const ctx=captureCanvas.getContext('2d');ctx.save();ctx.translate(w,0);ctx.scale(-1,1);ctx.drawImage(camera,0,0,w,h);ctx.restore();drawOutfit(ctx,w,h);const blob=await new Promise(r=>captureCanvas.toBlob(r,'image/jpeg',.9));if(!blob)throw new Error('Could not create photo.');await uploadPhotoBlob(blob);currentGallery='active';syncTabs();await renderGallery();showToast('Saved privately to your Tidefall Camera Roll.')}catch(e){console.error(e);showToast(`Save failed: ${e.message||'unknown error'}`)}finally{captureBtn.disabled=!stream;cameraStatus.textContent='Live camera stays on this device. Captured photos are stored privately in your Tidefall account.'}}
async function getPhotos(){if(!currentUser)return[];const{data,error}=await sb.from('wardrobe_photos').select('*').eq('state',currentGallery==='active'?'active':'recently_deleted').order('updated_at',{ascending:false});if(error)throw error;return data||[]}
async function signedPhotoUrl(path){const{data,error}=await sb.storage.from(BUCKET).createSignedUrl(path,3600);if(error)throw error;return data.signedUrl}
async function moveToRecentlyDeleted(p){const{error}=await sb.from('wardrobe_photos').update({state:'recently_deleted',deleted_at:new Date().toISOString(),posted:false}).eq('id',p.id);if(error)return showToast(error.message);await renderGallery();showToast('Moved to Recently Deleted.')}
async function restorePhoto(p){const{error}=await sb.from('wardrobe_photos').update({state:'active',deleted_at:null,posted:false}).eq('id',p.id);if(error)return showToast(error.message);await renderGallery();showToast('Photo restored. Moderation clock reset to 30 days.')}
async function markForShare(p){const{error}=await sb.from('wardrobe_photos').update({posted:true}).eq('id',p.id);if(error)return showToast(error.message);await renderGallery();showToast('Marked for sharing. Public Tidefall posts are the next moderation layer.')}
async function permanentlyDelete(p){const{error:s}=await sb.storage.from(BUCKET).remove([p.storage_path]);if(s)return showToast(s.message);const{error:r}=await sb.from('wardrobe_photos').delete().eq('id',p.id);if(r)return showToast(r.message);await renderGallery();showToast('Photo permanently deleted.')}
async function purgeExpired(){if(!currentUser)return;const cutoff=new Date(Date.now()-RECENTLY_DELETED_DAYS*86400000).toISOString(),{data,error}=await sb.from('wardrobe_photos').select('id,storage_path,deleted_at').eq('state','recently_deleted').lt('deleted_at',cutoff);if(error||!data?.length)return;for(const p of data){const{error:e}=await sb.storage.from(BUCKET).remove([p.storage_path]);if(!e)await sb.from('wardrobe_photos').delete().eq('id',p.id)}}
async function renderGallery(){gallery.innerHTML='';if(!currentUser){emptyGallery.classList.add('show');return}emptyGallery.classList.remove('show');try{await purgeExpired();const photos=await getPhotos();emptyGallery.classList.toggle('show',!photos.length);for(const p of photos){const card=document.createElement('article');card.className='photo-card';const img=document.createElement('img');img.alt='Tidefall Wardrobe photo';img.src=await signedPhotoUrl(p.storage_path);let stateText;if(p.state==='recently_deleted'){const purgeAt=addDays(p.deleted_at,RECENTLY_DELETED_DAYS);stateText=`Recently Deleted · ${daysRemaining(purgeAt)} days until permanent deletion`}else if(Date.now()<=new Date(p.moderation_until).getTime())stateText=`Moderation storage · ${daysRemaining(p.moderation_until)} days remaining`;else stateText='Private gallery storage';const meta=document.createElement('div');meta.className='photo-meta';const title=p.outfit==='riptide'?'Riptide':p.outfit==='proving'?'Proving Ground':'Brannor';meta.innerHTML=`<strong>${title}</strong><small>${formatDate(p.created_at)}<br>${stateText}</small><div class="photo-actions"></div>`;const actions=meta.querySelector('.photo-actions');if(p.state==='active'){const post=document.createElement('button');post.textContent=p.posted?'Post queued':'Post';post.disabled=p.posted;post.onclick=()=>markForShare(p);const remove=document.createElement('button');remove.className='danger';remove.textContent='Delete';remove.onclick=()=>moveToRecentlyDeleted(p);actions.append(post,remove)}else{const restore=document.createElement('button');restore.textContent='Restore';restore.onclick=()=>restorePhoto(p);const remove=document.createElement('button');remove.className='danger';remove.textContent='Delete Permanently';remove.onclick=()=>permanentlyDelete(p);actions.append(restore,remove)}card.append(img,meta);gallery.appendChild(card)}}catch(e){console.error(e);emptyGallery.textContent='Could not load your Camera Roll.';emptyGallery.classList.add('show');showToast(e.message||'Camera Roll failed to load.')}}
startCameraBtn.addEventListener('click',startCamera);captureBtn.addEventListener('click',capturePhoto);document.querySelectorAll('.outfit-choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.outfit-choice').forEach(i=>i.classList.remove('active'));b.classList.add('active');currentOutfit=b.dataset.outfit;outfitOverlay.className=`outfit-overlay outfit-${currentOutfit}`;outfitLabel.textContent=b.dataset.label}));document.querySelectorAll('.gallery-tab').forEach(t=>t.addEventListener('click',async()=>{currentGallery=t.dataset.gallery;syncTabs();await renderGallery()}));sb.auth.onAuthStateChange(()=>refreshAuth());window.addEventListener('beforeunload',stopCamera);refreshAuth();