const RECENTLY_DELETED_DAYS=30,BUCKET='wardrobe-private',sb=window.tidefallSupabase;
const camera=document.getElementById('camera'),cameraStage=document.getElementById('cameraStage'),arCanvas=document.getElementById('arCanvas'),trackingBadge=document.getElementById('trackingBadge'),startCameraBtn=document.getElementById('startCamera'),captureBtn=document.getElementById('capturePhoto'),cameraStatus=document.getElementById('cameraStatus'),cameraPlaceholder=document.getElementById('cameraPlaceholder'),captureCanvas=document.getElementById('captureCanvas'),gallery=document.getElementById('gallery'),emptyGallery=document.getElementById('emptyGallery'),toast=document.getElementById('wardrobeToast'),authGateTitle=document.getElementById('authGateTitle'),authGateText=document.getElementById('authGateText'),accountLink=document.getElementById('accountLink');
let stream=null,currentGallery='active',currentUser=null,currentOutfit='brannor',poseLandmarker=null,poseInitPromise=null,smoothedPose=null,lastVideoTime=-1,trackingRaf=0;
const garmentSources={brannor:'assets/wardrobe/brannor-top.svg',riptide:'assets/wardrobe/riptide-top.svg',proving:'assets/wardrobe/proving-top.svg'};
const garments={};
for(const[name,src]of Object.entries(garmentSources)){const img=new Image();img.src=src;garments[name]=img}
const addDays=(d,n)=>new Date(d).getTime()+n*86400000;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function showToast(m){if(!toast)return;toast.textContent=m;toast.classList.add('show');clearTimeout(window.__wardrobeToast);window.__wardrobeToast=setTimeout(()=>toast.classList.remove('show'),2800)}
function formatDate(v){return new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))}
function daysRemaining(v){return Math.max(0,Math.ceil((new Date(v).getTime()-Date.now())/86400000))}
function syncTabs(){document.querySelectorAll('.gallery-tab').forEach(t=>t.classList.toggle('active',t.dataset.gallery===currentGallery))}
function setTracking(text,locked=false){trackingBadge.textContent=text;trackingBadge.classList.add('show');trackingBadge.classList.toggle('locked',locked)}
async function refreshAuth(){const{data:{user}}=await sb.auth.getUser();currentUser=user||null;startCameraBtn.disabled=false;if(stream)captureBtn.disabled=false;if(currentUser){authGateTitle.textContent='Signed in';authGateText.textContent=currentUser.email?`Photos will save privately to ${currentUser.email}`:'Photos will save privately to your Tidefall account.';accountLink.textContent='My Account';emptyGallery.textContent='No photos here yet.'}else{authGateTitle.textContent='Camera ready';authGateText.innerHTML='You can use the Wardrobe without an account. <a href="account.html" style="color:#fff;text-decoration:underline">Sign in or create an account</a> to save photos.';accountLink.textContent='Sign In';emptyGallery.textContent='Sign in to load your Camera Roll.'}await renderGallery()}
async function initPoseTracker(){if(poseLandmarker)return poseLandmarker;if(poseInitPromise)return poseInitPromise;poseInitPromise=(async()=>{const{FilesetResolver,PoseLandmarker}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/+esm');const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm');const opts={baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task',delegate:'GPU'},runningMode:'VIDEO',numPoses:1,minPoseDetectionConfidence:.72,minPosePresenceConfidence:.72,minTrackingConfidence:.72};try{return poseLandmarker=await PoseLandmarker.createFromOptions(vision,opts)}catch{opts.baseOptions.delegate='CPU';return poseLandmarker=await PoseLandmarker.createFromOptions(vision,opts)}})();try{return await poseInitPromise}catch(e){poseInitPromise=null;throw e}}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;camera.srcObject=null;cameraPlaceholder.classList.remove('hidden');captureBtn.disabled=true;startCameraBtn.textContent='Start Camera';smoothedPose=null;trackingBadge.classList.remove('show','locked');if(trackingRaf)cancelAnimationFrame(trackingRaf);trackingRaf=0;if(arCanvas){const c=arCanvas.getContext('2d');c.clearRect(0,0,arCanvas.width,arCanvas.height)}}
async function startCamera(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera is not supported in this browser.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:1600}},audio:false});camera.srcObject=stream;await camera.play().catch(()=>{});cameraPlaceholder.classList.add('hidden');captureBtn.disabled=false;startCameraBtn.textContent='Camera On';setTracking('Loading fit…');cameraStatus.textContent='Camera ready. Loading body tracking…';await initPoseTracker();cameraStatus.textContent='Fit ready. Keep your face and shoulders visible.';startTrackingLoop()}catch(e){console.error(e);cameraStatus.textContent='Camera access was blocked or unavailable. Check camera permission and try again.';showToast('Camera could not start.')}}
function smooth(next){if(!smoothedPose||smoothedPose.length!==next.length){smoothedPose=next.map(p=>({...p}));return}const a=.32;smoothedPose=next.map((p,i)=>({...p,x:smoothedPose[i].x+(p.x-smoothedPose[i].x)*a,y:smoothedPose[i].y+(p.y-smoothedPose[i].y)*a,z:smoothedPose[i].z+(p.z-smoothedPose[i].z)*a}))}
function midpoint(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function poseUsable(p){if(!p)return false;const required=[0,11,12];if(!required.every(i=>p[i]&&(p[i].visibility??1)>.66))return false;const ls=p[11],rs=p[12],nose=p[0],sc=midpoint(ls,rs),sw=dist(ls,rs);if(sw<.065)return false;if(nose.y>=sc.y+.02)return false;if(Math.abs(nose.x-sc.x)>sw*.72)return false;const hipsGood=[23,24].every(i=>p[i]&&(p[i].visibility??1)>.42);if(hipsGood){const hc=midpoint(p[23],p[24]);if(hc.y<=sc.y+.06)return false}return true}
function resizeAr(){const w=Math.max(1,Math.round(cameraStage.clientWidth)),h=Math.max(1,Math.round(cameraStage.clientHeight));if(arCanvas.width!==w||arCanvas.height!==h){arCanvas.width=w;arCanvas.height=h}}
function displayPoint(lm){const dw=arCanvas.width,dh=arCanvas.height,sw=camera.videoWidth||dw,sh=camera.videoHeight||dh,s=Math.max(dw/sw,dh/sh),rw=sw*s,rh=sh*s,ox=(dw-rw)/2,oy=(dh-rh)/2;return{x:ox+lm.x*rw,y:oy+lm.y*rh}}
function rawPoint(lm,w,h){return{x:lm.x*w,y:lm.y*h}}
function uprightAngle(a){while(a>Math.PI/2)a-=Math.PI;while(a<-Math.PI/2)a+=Math.PI;return a}
function drawGarment(ctx,pose,mapper,name=currentOutfit){if(!poseUsable(pose))return false;const img=garments[name];if(!img?.complete)return false;const ls=mapper(pose[11]),rs=mapper(pose[12]),sc=midpoint(ls,rs),shoulderW=dist(ls,rs);if(shoulderW<20)return false;
let torsoH=shoulderW*1.28;
if(pose[23]&&pose[24]&&(pose[23].visibility??1)>.42&&(pose[24].visibility??1)>.42){const lh=mapper(pose[23]),rh=mapper(pose[24]),hc=midpoint(lh,rh),rawTorso=hc.y-sc.y;if(rawTorso>shoulderW*.45)torsoH=clamp(rawTorso,shoulderW*.8,shoulderW*1.75)}
const angle=uprightAngle(Math.atan2(rs.y-ls.y,rs.x-ls.x));
const drawW=shoulderW*1.08,drawH=torsoH*1.18;
ctx.save();ctx.translate(sc.x,sc.y);ctx.rotate(angle);ctx.globalAlpha=.97;ctx.drawImage(img,-drawW/2,-drawH*.135,drawW,drawH);ctx.restore();return true}
function renderAr(){resizeAr();const ctx=arCanvas.getContext('2d');ctx.clearRect(0,0,arCanvas.width,arCanvas.height);if(poseUsable(smoothedPose)){if(drawGarment(ctx,smoothedPose,displayPoint))setTracking('Fit locked',true);else setTracking('Loading costume…')}else if(stream)setTracking('Show face + shoulders')}
function startTrackingLoop(){if(trackingRaf)cancelAnimationFrame(trackingRaf);const loop=()=>{if(!stream||!poseLandmarker)return;if(camera.readyState>=2&&camera.currentTime!==lastVideoTime){lastVideoTime=camera.currentTime;try{const result=poseLandmarker.detectForVideo(camera,performance.now());if(result.landmarks?.[0])smooth(result.landmarks[0]);else smoothedPose=null}catch(e){console.warn(e);smoothedPose=null}}renderAr();trackingRaf=requestAnimationFrame(loop)};trackingRaf=requestAnimationFrame(loop)}
async function uploadPhotoBlob(blob){const id=crypto.randomUUID(),path=`${currentUser.id}/${id}.jpg`;const{error:u}=await sb.storage.from(BUCKET).upload(path,blob,{contentType:'image/jpeg',upsert:false,cacheControl:'3600'});if(u)throw u;const{error:r}=await sb.from('wardrobe_photos').insert({id,user_id:currentUser.id,storage_path:path,outfit:currentOutfit,state:'active',posted:false});if(r){await sb.storage.from(BUCKET).remove([path]);throw r}return id}
async function capturePhoto(){if(!stream||!camera.videoWidth)return;if(!currentUser){showToast('Sign in to save this photo to your Camera Roll.');location.href='account.html?return=wardrobe.html';return}if(!poseUsable(smoothedPose)){showToast('Step into frame so your face and shoulders are visible.');return}captureBtn.disabled=true;cameraStatus.textContent='Saving securely…';try{const w=camera.videoWidth,h=camera.videoHeight;captureCanvas.width=w;captureCanvas.height=h;const ctx=captureCanvas.getContext('2d');ctx.drawImage(camera,0,0,w,h);drawGarment(ctx,smoothedPose,p=>rawPoint(p,w,h));const blob=await new Promise(r=>captureCanvas.toBlob(r,'image/jpeg',.92));if(!blob)throw new Error('Could not create photo.');await uploadPhotoBlob(blob);currentGallery='active';syncTabs();await renderGallery();showToast('Saved privately to your Tidefall Camera Roll.')}catch(e){console.error(e);showToast(`Save failed: ${e.message||'unknown error'}`)}finally{captureBtn.disabled=!stream;cameraStatus.textContent='Fit ready. Keep your face and shoulders visible.'}}
async function getPhotos(){if(!currentUser)return[];const{data,error}=await sb.from('wardrobe_photos').select('*').eq('state',currentGallery==='active'?'active':'recently_deleted').order('updated_at',{ascending:false});if(error)throw error;return data||[]}
async function signedPhotoUrl(path){const{data,error}=await sb.storage.from(BUCKET).createSignedUrl(path,3600);if(error)throw error;return data.signedUrl}
async function moveToRecentlyDeleted(p){const{error}=await sb.from('wardrobe_photos').update({state:'recently_deleted',deleted_at:new Date().toISOString(),posted:false}).eq('id',p.id);if(error)return showToast(error.message);await renderGallery();showToast('Moved to Recently Deleted.')}
async function restorePhoto(p){const{error}=await sb.from('wardrobe_photos').update({state:'active',deleted_at:null,posted:false}).eq('id',p.id);if(error)return showToast(error.message);await renderGallery();showToast('Photo restored. Moderation clock reset to 30 days.')}
async function markForShare(p){const{error}=await sb.from('wardrobe_photos').update({posted:true}).eq('id',p.id);if(error)return showToast(error.message);await renderGallery();showToast('Marked for sharing. Public Tidefall posts are the next moderation layer.')}
async function permanentlyDelete(p){const{error:s}=await sb.storage.from(BUCKET).remove([p.storage_path]);if(s)return showToast(s.message);const{error:r}=await sb.from('wardrobe_photos').delete().eq('id',p.id);if(r)return showToast(r.message);await renderGallery();showToast('Photo permanently deleted.')}
async function purgeExpired(){if(!currentUser)return;const cutoff=new Date(Date.now()-RECENTLY_DELETED_DAYS*86400000).toISOString(),{data,error}=await sb.from('wardrobe_photos').select('id,storage_path,deleted_at').eq('state','recently_deleted').lt('deleted_at',cutoff);if(error||!data?.length)return;for(const p of data){const{error:e}=await sb.storage.from(BUCKET).remove([p.storage_path]);if(!e)await sb.from('wardrobe_photos').delete().eq('id',p.id)}}
async function renderGallery(){gallery.innerHTML='';if(!currentUser){emptyGallery.classList.add('show');return}emptyGallery.classList.remove('show');try{await purgeExpired();const photos=await getPhotos();emptyGallery.classList.toggle('show',!photos.length);for(const p of photos){const card=document.createElement('article');card.className='photo-card';const img=document.createElement('img');img.alt='Tidefall Wardrobe photo';img.src=await signedPhotoUrl(p.storage_path);let stateText;if(p.state==='recently_deleted'){const purgeAt=addDays(p.deleted_at,RECENTLY_DELETED_DAYS);stateText=`Recently Deleted · ${daysRemaining(purgeAt)} days until permanent deletion`}else if(p.moderation_until&&Date.now()<=new Date(p.moderation_until).getTime())stateText=`Moderation storage · ${daysRemaining(p.moderation_until)} days remaining`;else stateText='Private gallery storage';const title=p.outfit==='riptide'?'Riptide':p.outfit==='proving'?'Proving Ground':p.outfit==='brannor'?'Brannor':'Camera Roll';const meta=document.createElement('div');meta.className='photo-meta';meta.innerHTML=`<strong>${title}</strong><small>${formatDate(p.created_at)}<br>${stateText}</small><div class="photo-actions"></div>`;const actions=meta.querySelector('.photo-actions');if(p.state==='active'){const post=document.createElement('button');post.textContent=p.posted?'Post queued':'Post';post.disabled=p.posted;post.onclick=()=>markForShare(p);const remove=document.createElement('button');remove.className='danger';remove.textContent='Delete';remove.onclick=()=>moveToRecentlyDeleted(p);actions.append(post,remove)}else{const restore=document.createElement('button');restore.textContent='Restore';restore.onclick=()=>restorePhoto(p);const remove=document.createElement('button');remove.className='danger';remove.textContent='Delete Permanently';remove.onclick=()=>permanentlyDelete(p);actions.append(restore,remove)}card.append(img,meta);gallery.appendChild(card)}}catch(e){console.error(e);emptyGallery.textContent='Could not load your Camera Roll.';emptyGallery.classList.add('show');showToast(e.message||'Camera Roll failed to load.')}}
startCameraBtn.addEventListener('click',startCamera);captureBtn.addEventListener('click',capturePhoto);document.querySelectorAll('.outfit-choice[data-outfit]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.outfit-choice').forEach(i=>i.classList.remove('active'));b.classList.add('active');currentOutfit=b.dataset.outfit;renderAr()}));document.querySelectorAll('.gallery-tab').forEach(t=>t.addEventListener('click',async()=>{currentGallery=t.dataset.gallery;syncTabs();await renderGallery()}));sb.auth.onAuthStateChange(()=>refreshAuth());window.addEventListener('beforeunload',stopCamera);refreshAuth();